; PHP Configuration for Laravel

[PHP]
post_max_size        = 50M
upload_max_filesize  = 50M
max_execution_time   = 300
memory_limit         = 256M
display_errors       = Off
log_errors           = On
error_log            = /var/log/php_errors.log

[Date]
date.timezone = Asia/Jakarta
